### ISSUE TITLE
evaluate.py does not accept empty line numbers

### ISSUE THREAD

**Issue by jderehag** [KTH/CodRep-competition#24]
As stated in the README:
"Your program does not have to predict something for all input files, if there is no clear answer, simply don't output anything, the error computation takes that into account, more information about this in Loss function below."

This is a bit ambiguous, does it mean that the output should be skipped altogether or that one could output just the filename with no line number?
Either case, it should probably either be fixed or clarified in the README.

The latter does *not* work (full path omitted):
echo "CodRep-competition/Datasets/Dataset1/Tasks/2703.txt 35" | python evaluate.py 
Total files: 34096
Average line error: 0.999970671046 (the lower, the better)
Recall@1: 2.93289535429e-05 (the higher, the better)

echo "CodRep-competition/Datasets/Dataset1/Tasks/2703.txt" | python evaluate.py
Traceback (most recent call last):
  File "evaluate.py", line 183, in <module>
    main()
  File "evaluate.py", line 168, in main
    prediction = inputs[1]
IndexError: list index out of range

echo "CodRep-competition/Datasets/Dataset1/Tasks/2703.txt " | python evaluate.py
Traceback (most recent call last):
  File "evaluate.py", line 183, in <module>
    main()
  File "evaluate.py", line 168, in main
    prediction = inputs[1]
IndexError: list index out of range

**Comment by chenzimin** [comment]
> This is a bit ambiguous, does it mean that the output should be skipped altogether or that one could output just the filename with no line number?

It means that the output should be skipped altogether.

>Either case, it should probably either be fixed or clarified in the README.

I have updated README in commit [be5bb4d](https://github.com/KTH/CodRep-competition/commit/be5bb4d9b74a4d64b1ead75f7602e458bbafc657).
